name: meplus
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #flutter:
  #  sdk: flutter
  #flutter_localizations:
  #  sdk: flutter

  cupertino_icons: ^1.0.1
  url_launcher: ^5.7.2
  uni_links: ^0.4.0
  firebase_core: ^0.4.4
  firebase_core_web: ^0.1.1+2
  #firebase_core: ^0.5.0+1
  #firebase_auth: ^0.18.1+2
  firebase_auth: ^0.16.1
  firebase_auth_web: ^0.1.3+1
  google_sign_in: ^4.5.4
  font_awesome_flutter: ^8.10.0
  http: ^0.12.0+4
  provider: ^4.3.1
  #firebase_database: ^3.1.6
  cloud_firestore: ^0.13.7  # ถ้าต้องการใช้ firebase data ให้ไปปิด Firestore
  cloud_firestore_web: ^0.1.1+2
  #flutter_line_sdk: ^1.2.9
  #flutter_line_sdk: ^2.0.0
  styled_widget: ^0.2.2

  rxdart: ^0.23.1
  data_tables: ^1.0.1
  flushbar: ^1.9.1
  shimmer: ^1.0.1
  bubble_bottom_bar: ^1.2.0
  intl: ^0.16.0
  connectivity: ^0.4.6+1
  data_connection_checker: ^0.3.4
  nice_button: ^0.1.7
  provider_architecture: ^1.0.3
  #flutter_line_sdk: ^1.3.0
  #flutter_line_sdk: ^1.2.9
  logger: ^0.8.3
  apple_sign_in: ^0.1.0

  date_range_picker: ^1.0.5
  auto_size_text: ^2.0.2
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.5.0
  dio: ^3.0.10
  #uuid: 2.0.1
  device_info: ^0.4.1+4
  google_fonts: ^0.3.2
  #firebase_admob: ^0.10.0-dev.1
  flare_flutter: ^2.0.3
  international_phone_input: ^1.0.4
  #flutter_launcher_icons: "^0.7.3"
  flutter_launcher_icons: 0.9.1
  flutter_sheet_localization: ^2.0.0
  google_maps_flutter: ^0.5.20+6
  #palette: ^0.2.0+1
  #barcode_scan: ^1.0.0
  #bottom_navy_bar:
  #  path: ../
  #firebase_core: ^0.5.0+1
  #firebase_database: ^4.1.1
  #firebase_auth: ^0.18.1+2
  #splashscreen : 1.2.0
  #flutter_signin_button: ^1.0.0
  image_picker: ^0.6.2+3
  solid_bottom_sheet: ^0.1.10
  #image_picker_modern: ^0.4.12+2
  firebase_storage: ^3.1.6
  #firebase_storage: ^3.1.1

  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  #rubber: 0.4.0
  rubber: ^1.0.1
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  flutter_rating_bar: 3.2.0+1
  numberpicker: ^1.0.0
  flare_splash_screen: 3.0.1
  #flutter_svg: 0.18.0
  flutter_svg: ^0.20.0-nullsafety.3
  #flutter_svg: ^0.20.0
  #image: ^2.1.14
  image: ^3.0.2
  crypto: ^3.0.0
  uuid: ^3.0.4
  #xml: ^4.2.0
  xml: ^5.0.0-nullsafety.0
  ntp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
     - assets/
     - assets/images/
     - assets/icons/
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
